# -*- coding: utf-8 -*-
"""exercicios_T12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GK_2bNYtgBrH6dY5wJGy5pCApInsdPcV
"""

#exercicio 1
numero = int(input("digite um numero inteiro: "))


while numero >= 0:
    print(numero)
    numero = numero - 1

print("Fim do loop!")

# exercicio 2
nomes = []

for i in range(3):
  nome = input(f"digite o {i+1}º: ")
  nomes.append(nome)

print("\nNomes em maiúsculo")
for nome in nomes:
  print(nome.upper())

quantidade = int(input("Quantas notas deseja digitar? "))

soma = 0

for i in range(quantidade):
    nota = float(input(f"Digite a nota {i + 1}: "))
    soma += nota

media = soma / quantidade

print(f"\nMédia final: {media:.2f}")

if media >= 7:
    print("APROVADO!")
else:
    print("REPROVADO!")